region: us-east-1

function_name: au_trade_leads
handler: service.handler
role: lambda_api
runtime: python3.8
description: Fetches trade leads links, scrapes data for each link from HTML page, builds a single JSON document, and stores it in S3

timeout: 600
memory_size: 128
